### ISSUE TITLE
Add a spec with selenium implementation

### ISSUE THREAD

**Issue by zabil** [getgauge/template-java#1]
Most java users use gauge java with selenium for writing tests. Introduce a sample spec that uses selenium for testing and modify this template to use gradle as the build tool.

**Comment by BugDiver** [comment]
We can do one of the following
1. Make the java_gradle template as default (config)?

Ex: In the config file
`java = https://github.com/getgauge/template-java-gradle/releases/latest/download/java_gradle.zip`

2. rename template-java-gradle repo and its artifacts as `template-java`

**Comment by zabil** [comment]
There is one downside to moving the example completely to gradle. There is extensive reference in the current documentation to run examples using

```
gauge run spec
```

There is value in having the simple vowel example too. So it may be good to merge both of them. This way there is little change to our getting started documentation process.

So can we have two folders. i.e. `specs` for the vowels example and `e2e` for the selenium test.
The user can run the vowels example using

```
gauge run specs
```

and the the selenium tests using

```
./gradlew test
```
(which internally uses the e2e folder)
We might need to look at the implementation folder separating.

**Comment by BugDiver** [comment]
We can do this (having to folders for specs).
But we have to keep a template for simple vowels spec  (for all languages ) because our FT creates a sample project, for each scenario.

**Comment by zabil** [comment]
Closing this a this will need a lot of change to our documentation and testing
